---
title: "eds221-afternoon"
format: html
editor: visual
---


```{r}
dog_menu <- function(enter_dog_name){
  my_subset <- filter(dog_choice, dog_name == enter_dog_name)
  print(paste("My name is", my_subset$dog_name, "and my favorite food is", my_subset$food))
}
```
```{r}
dog_menu(enter_dog_name = "Waffle")
```

# Function with a for loop 

```{r}
df_means <- function(df) {
  for (i in seq_along(df)) {
    col_mean <- mean(df[[i]], na.rm = TRUE)
    column_name <- colnames(df[i])
    print(paste("The mean value of", column_name, "is", col_mean))
  }
}
```
```{r}
df_means(df = mtcars)
```

create a function to calculate the betz limit 
air density: kg / m^3 
rotor radius: meters 
wind velocity: m/s 
power: watts 

```{r}
calculate_betz_windpower <- function(air_density, rotor_radius, wind_velocity){
  0.3 * air_density * pi * (rotor_radius ^ 2) * (wind_velocity ^ 3)
}
```
```{r}
calculate_betz_windpower(air_density = 1.2, rotor_radius = 30, wind_velocity = 50)
```

```{r}
calculate_betz_windpower <- function(air_density, rotor_radius, wind_velocity){
  if (wind_velocity > 60){
    warning("are u sure?")
  }
  if (rotor_radius < 0){
    stop("rotor radius must be a positive value")
  }
   0.3 * air_density * pi * (rotor_radius ^ 2) * (wind_velocity ^ 3)
}
```

```{r}
calculate_betz_windpower(air_density = 1.2, rotor_radius = -20, wind_velocity = 1060)

```



